/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.ConnectionConfig;
import dao.ConnectionFactory;
import dao.UsersDao;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.User;

/**
 *
 * @author Novo
 */
public class ViewScreen extends javax.swing.JFrame {

    final ConnectionConfig config = new ConnectionConfig(
            "remotemysql.com",
            "xoMuXbAysR",
            "L3XulXHzPC",
            "3306",
            "xoMuXbAysR"
    );

    UsersDao usersDao;

    ArrayList<User> users = new ArrayList();

    /**
     * Creates new form ViewScreen
     */
    public ViewScreen() {
        defineConnection();

        initComponents();
    }

    private void defineConnection() {
        try {
            Connection connection = ConnectionFactory.getConnection(config);
            Statement statement = ConnectionFactory.getStatement(connection);

            System.out.println("Successful connected to MySQL Database");

            usersDao = new UsersDao(statement);

            System.out.println("Successful created UsersDao");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tentativa de acessar um usuário com ID inválido");
        }
    }

    private void loadUsers() {
        try {
            // On load window, load users
            users = usersDao.getAll();

            DefaultListModel<String> model = new DefaultListModel();

            for (int i = 0; i < users.size(); i++) {
                final User user = users.get(i);

                model.addElement(user.getName() + ", idade " + user.getAge() + ", ID = " + user.getId());
            }

            jUsersList.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(ViewScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jUsernameTextField = new javax.swing.JTextField();
        jAgeTextField = new javax.swing.JTextField();
        jUserAction = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jUsersList = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jIdToDeleteTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jDeleteUser = new javax.swing.JButton();
        jIdTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jUsernameTextField.setToolTipText("Nome de usuário");

        jAgeTextField.setToolTipText("Idade");

        jUserAction.setText("Criar Usuário");
        jUserAction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jUserActionMouseClicked(evt);
            }
        });

        jUsersList.setName("jUsersList"); // NOI18N
        jScrollPane1.setViewportView(jUsersList);

        jLabel1.setText("Nome de usuário");

        jLabel2.setText("Idade");

        jLabel3.setText("ID do usuário que deseja deletar");

        jDeleteUser.setText("Deletar usuário");
        jDeleteUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDeleteUserMouseClicked(evt);
            }
        });

        jIdTextField.setToolTipText("Idade");
        jIdTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jIdTextFieldKeyReleased(evt);
            }
        });

        jLabel4.setText("ID (Opcional) - Preencha esse campo se for atualizar um usuário");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jUsernameTextField)
                    .addComponent(jAgeTextField)
                    .addComponent(jSeparator1)
                    .addComponent(jIdTextField)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jUserAction, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jIdToDeleteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jDeleteUser))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAgeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jUserAction, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jIdToDeleteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jUserActionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUserActionMouseClicked
        int age = Integer.parseInt(jAgeTextField.getText());
        String username = jUsernameTextField.getText();
        String id = jIdTextField.getText();

        try {
            if (id.isEmpty()) {
                usersDao.createUser(new User(username, age), false);
            } else {
                usersDao.updateUser(Integer.parseInt(id), new User(username, age));
            }

            loadUsers();
        } catch (SQLException ex) {
            Logger.getLogger(ViewScreen.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(ViewScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jUserActionMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        loadUsers();
    }//GEN-LAST:event_formWindowActivated

    private void jIdTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jIdTextFieldKeyReleased
        if(jIdTextField.getText().isEmpty()){
            jUserAction.setText("Criar usuário");
        } else {
            jUserAction.setText("Atualizar usuário");
        }
    }//GEN-LAST:event_jIdTextFieldKeyReleased

    private void jDeleteUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDeleteUserMouseClicked
        String idToDelete = jIdToDeleteTextField.getText();
        
        try {
            usersDao.deleteUser(Integer.parseInt(idToDelete));
            
            loadUsers();
        } catch (Exception ex) {
            Logger.getLogger(ViewScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jDeleteUserMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jAgeTextField;
    private javax.swing.JButton jDeleteUser;
    private javax.swing.JTextField jIdTextField;
    private javax.swing.JTextField jIdToDeleteTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jUserAction;
    private javax.swing.JTextField jUsernameTextField;
    private javax.swing.JList<String> jUsersList;
    // End of variables declaration//GEN-END:variables
}
